[package]
name = "rusty_vimacs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.3"
nix = "0.24.1"
term_size = "0.3.2"
